Sync `upstream/master` (#48)
* Explicitly install a Rust toolchain for cargo-outdated job

Debugging a recent cargo-outdated bug, it would have been nice not to
wonder whether a rustc version change in GitHub's runner image was a
contributing factor.

* Resolve unexpected_cfgs warning

    warning: unexpected `cfg` condition name: `exhaustive`
     --> tests/exhaustive.rs:1:8
      |
    1 | #![cfg(exhaustive)]
      |        ^^^^^^^^^^
      |
      = help: expected names are: `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, `unix`, `windows`
      = help: consider using a Cargo feature instead or adding `println!("cargo::rustc-check-cfg=cfg(exhaustive)");` to the top of the `build.rs`
      = note: see <https://doc.rust-lang.org/nightly/cargo/reference/build-scripts.html#rustc-check-cfg> for more information about checking conditional configuration
      = note: `#[warn(unexpected_cfgs)]` on by default

* Move allow(unexpected_cfgs) to the crate where cfg(exhaustive) is used

* Skip rerunning build script on library code changes

* Ignore cast_possible_truncation pedantic clippy lint in test

    warning: casting `usize` to `u32` may truncate the value on targets with 64-bit wide pointers
      --> tests/exhaustive.rs:20:25
       |
    20 |             let batch = counter.fetch_add(1, Ordering::Relaxed) as u32;
       |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = help: if this is intentional allow the lint with `#[allow(clippy::cast_possible_truncation)]` ...
       = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cast_possible_truncation
       = note: `-W clippy::cast-possible-truncation` implied by `-W clippy::pedantic`
       = help: to override `-W clippy::pedantic` add `#[allow(clippy::cast_possible_truncation)]`
    help: ... or use `try_from` and handle the error accordingly
       |
    20 |             let batch = u32::try_from(counter.fetch_add(1, Ordering::Relaxed));
       |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* Mark exhaustive test #[ignore] in non-cfg(exhaustive)

* Fill in ignore reasons in all #[ignore] attributes

* Upload CI Cargo.lock for reproducing failures

* Prevent upload-artifact step from causing CI failure

This step has been failing way more than reasonable across my various repos.

    With the provided path, there will be 1 file uploaded
    Artifact name is valid!
    Root directory input is valid!
    Attempt 1 of 5 failed with error: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact. Retrying request in 3000 ms...
    Attempt 2 of 5 failed with error: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact. Retrying request in 6029 ms...
    Attempt 3 of 5 failed with error: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact. Retrying request in 8270 ms...
    Attempt 4 of 5 failed with error: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact. Retrying request in 12577 ms...
    Error: Failed to CreateArtifact: Failed to make request after 5 attempts: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact

* Remove **/*.rs.bk from project-specific gitignore

Cargo stopped generating this in its project template 5 years ago. It
would belong in a global gitignore instead.

* More precise gitignore patterns

* Update rand crate to 0.9

* Unset doc-scrape-examples for lib target

False is the default value since Cargo PR 11499.

* Fix clippy warnings

---------

Co-authored-by: David Tolnay <dtolnay@gmail.com>